# drag or resize constants
NONE = 0
DRAG = 1
RESIZE = 2

# colors
MAGNET_LINE_COLOR = "#646464"
SPECIAL_LINE_COLOR = "#969696"
GRID_COLOR = "#C0C0C0"
DEFAULT_ARROW_COLOR = "#7F7F7F"
DEFAULT_SELECTED_ARROW_COLOR = "#3A3A3A"
WIDGET_BORDER_COLOR = CONTEXT_MENU_BORDER_COLOR = "#7F7F7F"

WHITE = "#FFFFFF"
BLACK = "#000000"

# arrow start and end
FROM_AND_TO_NEAREST_LINE = 1
FROM_AND_TO_CENTER = 2

OFFSET_MAGNET = 5

# grid
GRID_STEP = 20